# site name
prefixName: Hello, नमस्ते !
siteName: raylee
# favicon and site master avatar
favicon: https://cdn.jsdelivr.net/gh/raylee-lilei/cdn@2.0/img/custom/logo.png
avatar: /img/custom/logo_1.png
url: https://raylee-lilei.github.io/
description: Live your life with passion! With some drive!
cdn: https://cdn.jsdelivr.net/gh/raylee-lilei/cdn@2.4
pjax: 1
# 1开启
mathjax: 0

notice: testing developing...
lazyloadImg: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  home: { path: /, fa: fa-home }
  article: { path: /archives, fa: fa-archive faa-shake, submenus: { 
    tech: {path: /categories/technology/, fa: fa-code }, 
    life: {path: /categories/life/, fa: fa-file-text-o }, 
    #resou: {path: /categories/resources/, fa: fa-cloud-download }, 
    think: {path: /categories/think/, fa: fa-commenting-o },
    link: {path: /categories/link/, fa: fa-book }
  } }
  list: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: { 
    book: {path: /tags/reading/, fa: fa-th-list faa-bounce }, 
    #fan: {path: /bangumi/, fa: fa-film faa-vertical }, 
    song: {path: /music/, fa: fa-headphones },
    atlas: {path: /tags/atlas/, fa: fa-photo }
  } }
  message: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  #friend : { path: /links/, fa: fa-link faa-shake }
  apprecial: { path: /donate/, fa: fa-heart faa-pulse }
  about: { path: /, fa: fa-leaf faa-wrench , submenus: { 
    me: {path: /about/, fa: fa-meetup}, 
    #theme: {path: /theme-sakura/, fa: iconfont icon-sakura },
    lab: {path: /lab/, fa: fa-cogs },
    sme: {path: /download/, fa: fas fa-download },
  } }
  offer: { path: /offer/, fa: fa-address-card }
  #download: { path: /download/, fa: fa-android faa-vertical }
  #RSS: { path: /atom.xml, fa: fa-rss faa-pulse }


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
  - https://cdn.jsdelivr.net/gh/raylee-lilei/cdn@1.9/img/cover/05.jpg.webp
  #- https://cdn.jsdelivr.net/gh/raylee-lilei/cdn@1.9/img/cover/01.jpg.webp
  #- https://cdn.jsdelivr.net/gh/raylee-lilei/cdn@1.9/img/cover/02.jpg.webp
  #- https://cdn.jsdelivr.net/gh/raylee-lilei/cdn@1.9/img/cover/03.jpg.webp
  - https://cdn.jsdelivr.net/gh/raylee-lilei/cdn@1.9/img/cover/04.jpg.webp
  #- https://cdn.jsdelivr.net/gh/raylee-lilei/cdn@1.9/img/cover/06.jpg.webp
  - https://cdn.jsdelivr.net/gh/raylee-lilei/cdn@2.9/img/download/narrative.jpg
  - https://cdn.jsdelivr.net/gh/raylee-lilei/cdn@3.1/img/download/home.jpg
  - https://cdn.jsdelivr.net/gh/raylee-lilei/cdn@3.1/img/download/tuzi.jpg

# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dot

# startdash url, title, desc img
startdash: 
  - {url: /theme-sakura/, title: Sakura, desc: create, img: /img/startdash/sakura.md.png}
  - {url: /, title: introduction, desc: blog, img: /img/startdash/charcter.png}
  - {url: /, title: raylee Mood House, desc: technology, img: /img/startdash/erji.png}



# your site build time or founded date
siteBuildingTime: 03/28/2020

#social  url, img PC端配置
social:
  github: {url: https://github.com/, img: /img/social/github.png}
  resume: {url: https://raylee-lilei.github.io/resume/, img: /img/social/jianshu.png}
  #sina: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/sina.png}
  QQ: {url: /#,qrcode: /img/custom/Jqq.png, img: /img/social/qq.png}
  wechatGZH: {url: /#, qrcode: /img/custom/WXGZHewm.jpg, img: /img/social/weixinGZH.jpg}
  wechat: {url: /#, qrcode: /img/custom/wechat.jpg, img: /img/social/wechat.png}
 # wechat2: {url: /#, qrcode: /img/custom/wechat.jpg, img: /img/social/wechat.png}

#social  url, img 移动端配置
msocial:
  github: {url: https://github.com/, fa: fa-github, color: 333}
  resume: {url: https://raylee-lilei.github.io/resume/, fa: fa-resume, color: dd4b39}
  qq: {url: https://wpa.qq.com/msgrd?v=3&uin=751301185&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}

donate:
  #paypal: https://www.paypal.me/hojuncn
  alipay: /img/custom/donate/ZFBry.png
  wechat: /img/custom/donate/WXry.png
  #wechatSQ: /img/custom/donate/WeChanSQ.jpg

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  url: https://cdn.jsdelivr.net/gh/honjun/hojun@1.2
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: Unbroken.mp4

aplayer: 
  id: 2660651585
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true

# Valine
valine: true
v_appId: Ax3mFW8rxWvley0eMkktAYqA-gzGzoHsz
v_appKey: Hk4wTcsQ3w4vou3F1LfiXsU9

